name: Badge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate badge
        run: |
          curl -s "https://img.shields.io/badge/Go-passing-passing?logo=github" > badge.svg
      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: badge.svg
